Learnathon-By-Geeky-Solutions/earendel

backend/Api/Framework/Infrastructure/Messaging/MessagingExtensions.cs, backend/Api/Framework/Infrastructure/Messaging/RabbitMQMessageBus.cs, backend/Api/Framework/Infrastructure/Messaging/RabbitMQOptions.cs, backend/Api/Framework/Infrastructure/OpenApi/ConfigureSwaggerOptions.cs, backend/Api/Module/Experties/Experties.Domain/Skill.cs, backend/Aspire/Aspire.sln, backend/Dockerfile, backend/docker-compose.yml, backend/menifest/aspire-deployment.yaml, backend/menifest/aspire-service.yaml, backend/menifest/backend-deployment.yaml, backend/menifest/backend-service.yaml, backend/menifest/grafana-data-persistentvolumeclaim.yaml, backend/menifest/grafana-deployment.yaml, backend/menifest/grafana-service.yaml, backend/menifest/node-exporter-deployment.yaml, backend/menifest/node-exporter-service.yaml, backend/menifest/postgres-data-persistentvolumeclaim.yaml, backend/menifest/postgres-deployment.yaml, backend/menifest/postgres-service.yaml, backend/menifest/prometheus-cm0-configmap.yaml, backend/menifest/prometheus-deployment.yaml, backend/menifest/prometheus-service.yaml, backend/menifest/rabbitmq-deployment.yaml, backend/menifest/rabbitmq-service.yaml, backend/menifest/redis-deployment.yaml, backend/menifest/redis-service.yaml, backend/prometheus.yml
**Added feature:**
1. Dockerize the Project
2. RabbitMQ
3. Grafana
4. prometheus
=> Merge Feature/docker-kubernetes into development

backend/Api/Module/Experties/Experties.Application/Seniorities/Search/v1/SearchSenioritySpecs.cs, backend/Api/Module/Experties/Experties.Application/Skills/Search/v1/SearchSkillSpecs.cs, backend/Api/Module/Experties/Experties.Application/Skills/Update/v1/UpdateSkillHandler.cs
Update Skills module to fetch records where deleted is null
=> fix: Update Seniorities module to fetch records where deleted is null

backend/Api/Module/Experties/Experties.Test/Rubric.cs
=> fix: fix rubric test errors

backend/Api/Module/Experties/Experties.Test/Skill.cs
=> fix: fix test error

Migrations/PGSql/obj/.EntityFrameworkCore.targets, backend/Api/Module/Interviews/Interviews.Application/Interviews/Create/v1/CreateInterviewCommand.cs, backend/Api/Module/Interviews/Interviews.Application/Interviews/Create/v1/CreateInterviewCommandValidator.cs, backend/Api/Module/Interviews/Interviews.Application/Interviews/Create/v1/CreateInterviewHandler.cs, backend/Api/Module/Interviews/Interviews.Application/Interviews/Search/v1/SearchInterviewSpecs.cs, backend/Api/Module/Interviews/Interviews.Application/Interviews/Search/v1/SearchInterviewsCommand.cs, backend/Api/Module/Interviews/Interviews.Application/Interviews/Update/v1/UpdateInterviewCommand.cs, backend/Api/Module/Interviews/Interviews.Application/Interviews/Update/v1/UpdateInterviewCommandValidator.cs, backend/Api/Module/Interviews/Interviews.Application/Interviews/Update/v1/UpdateInterviewHandler.cs, backend/Api/Module/Interviews/Interviews.Domain/Interview.cs, backend/Api/Module/Interviews/Interviews.Infrastructure/Persistence/InterviewsDbInitializer.cs, backend/Api/Module/Interviews/Interviews.Test/Interview.cs, backend/Api/Module/Notifications/Notifications.Application/Notifications/Search/v1/SearchNotificationSpecs.cs
Update on Interview Module by adding candidateId and jobId fields
=> refactor: add candidateId, jobId field on interview module

backend/Api/Module/Interviews/Interviews.Application/Interviews/Get/v1/GetInterviewHandler.cs, backend/Api/Module/Interviews/Interviews.Application/Interviews/Get/v1/InterviewResponse.cs, backend/Api/Module/Interviews/Interviews.Test/Interview.cs
Add candidateId, jobId on InterviewResponse
=> fix: Add candidateId, jobId on InterviewResponse

backend/Api/Module/Experties/Experties.Application/Rubrics/Search/v1/SearchRubricSpecs.cs, backend/Api/Module/Experties/Experties.Application/Skills/Create/v1/CreateSkillHandler.cs, backend/Api/Module/Experties/Experties.Application/Skills/Delete/v1/DeleteSkillHandler.cs, backend/Api/Module/Experties/Experties.Application/Skills/EventHandlers/SkillCreatedEventHandler.cs, backend/Api/Module/Experties/Experties.Application/Skills/Get/v1/GetSkillHandler.cs, backend/Api/Module/Experties/Experties.Application/Skills/Search/v1/SearchSkillSpecs.cs, backend/Api/Module/Experties/Experties.Application/Skills/Update/v1/UpdateSkillCommandValidator.cs, backend/Api/Module/Experties/Experties.Application/Skills/Update/v1/UpdateSkillHandler.cs, backend/Api/Module/Experties/Experties.Application/SubSkills/Delete/v1/DeleteSubSkillHandler.cs, backend/Api/Module/Experties/Experties.Application/SubSkills/Get/v1/GetSubSkillHandler.cs, backend/Api/Module/Experties/Experties.Application/SubSkills/Search/v1/SearchSubSkillSpecs.cs, backend/Api/Module/Experties/Experties.Application/SubSkills/Update/v1/UpdateSubSkillHandler.cs, backend/Api/Module/Experties/Experties.Test/Skill.cs
fix sonarcloud issues and works on code complexity
=> fix: fix few things

.github/workflows/build-and-publish.yml, .github/workflows/deploy.yml
=> chore(ci): split main.yml into deploy.yml and ci-cd.yml

.github/workflows/build-and-publish.yml
=> core: split ci/cd into two parts

backend/Shared/Authorization/TMPermissions.cs, backend/Shared/Authorization/TMResources.cs
=> refactor: Add interviewsignature permissions

backend/Shared/Authorization/TMPermissions.cs
=> fix: fix build errors

backend/Api/Framework/Infrastructure/Identity/Users/Services/UserService.cs, backend/Api/Framework/Infrastructure/SignalR/NotificationHub.cs, backend/Api/Module/Experties/Experties.Application/Rubrics/Search/v1/SearchRubricSpecs.cs, backend/Api/Module/Experties/Experties.Infrastructure/Messaging/SkillsCreatedConsumer.cs, backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Create/v1/CreateInterviewFeedbackCommandValidator.cs, backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Update/v1/UpdateInterviewFeedbackCommandValidator.cs, backend/Api/Module/Interviews/Interviews.Application/Interviews/Create/v1/CreateInterviewHandler.cs, backend/Api/Module/Interviews/Interviews.Application/Interviews/Update/v1/UpdateInterviewHandler.cs, backend/Api/Module/Interviews/Interviews.Domain/Interview.cs, backend/Api/Module/Interviews/Interviews.Domain/InterviewDto.cs, backend/Api/Module/Interviews/Interviews.Domain/InterviewFeedback.cs, backend/Api/Module/Interviews/Interviews.Infrastructure/Persistence/InterviewsDbInitializer.cs, backend/Api/Module/Interviews/Interviews.Test/Interview.cs, backend/Api/Module/Jobs/Jobs.Application/JobApplication/Delete/v1/DeleteJobApplicationHandler.cs, backend/Api/Module/Jobs/Jobs.Application/JobRequiredSkill/Delete/v1/DeleteJobRequiredSkillHandler.cs, backend/Api/Module/Jobs/Jobs.Application/JobRequiredSubskill/Delete/v1/DeleteJobRequiredSubskillHandler.cs, backend/Api/Module/Jobs/Jobs.Application/Jobs/Delete/v1/DeleteJobHandler.cs, backend/Api/Module/Jobs/Jobs.Application/Jobs/Update/v1/UpdateJobHandler.cs, backend/Api/Module/Jobs/Jobs.Domain/JobDetails.cs, backend/Api/Module/Jobs/Jobs.Domain/Jobs.cs, backend/Api/Module/Jobs/Jobs.Test/JobDomainTests.cs, backend/Api/Module/Jobs/Jobs.Test/JobHandlerTest.cs, backend/Api/Module/Jobs/Jobs.Test/JobsTests.cs, backend/Api/Module/Notifications/Notifications.Infrastructure/Messaging/NotificationConsumer.cs
=> fix: fix sonarcloud errors

.github/workflows/deploy.yml
increase script timeout on deployment
=> fix: increase script time on deployment

.github/workflows/deploy.yml
=> feat: remove timeout

.github/workflows/build-and-publish.yml, .github/workflows/deploy.yml, backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/SSLCommerzSuccessEndpoint.cs, backend/Api/Framework/Infrastructure/Identity/Users/Services/ExternalApiClient.cs, backend/Api/Module/CandidateLogic/JobView/JobViewService.cs, backend/Api/Module/Experties/Experties.Application/Skills/EventHandlers/SkillCreatedEventHandler.cs
1. Update Job Filtering Login
2. Fix Security issues
=> chore: add job filtering logic

.github/workflows/deploy.yml, backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/SSLCommerzSuccessEndpoint.cs, backend/Api/Framework/Infrastructure/Messaging/RabbitMqConsumerBase.cs, backend/Api/Module/CandidateLogic/JobView/JobViewService.cs, backend/Api/Module/Experties/Experties.Application/Skills/EventHandlers/SkillCreatedEventHandler.cs, backend/Api/Module/Experties/Experties.Infrastructure/Messaging/SkillsCreatedConsumer.cs, backend/Api/Module/Notifications/Notifications.Application/Notifications/Search/v1/SearchNotificationSpecs.cs
fix job filtering issues and sonarcloud issues
=> fix: fix job filtering issues and sonarcloud issues

backend/Api/Module/Evaluator/Evaluator.Application/Interviewer/Create/v1/CreateInterviewerAvailabilityCommandValidator.cs
fix available time format for interviewer
=> fix: fix available time format

backend/Api/Framework/Infrastructure/Identity/Tokens/TokenService.cs, backend/Dockerfile
=> fix docker copy issue

backend/Api/Module/Evaluator/Evaluator.Application/Interviewer/Create/v1/CreateInterviewerAvailabilityCommandValidator.cs, backend/Api/Module/Evaluator/Evaluator.Application/Interviewer/Create/v1/CreateInterviewerAvailabilityHandler.cs
fix available time format issue
=> fix: available time issues

src/app/admin-dashboard/hr/hr.component.ts, src/app/admin-dashboard/services/skill.service.ts, src/app/admin-dashboard/sidebar/sidebar.component.ts, src/app/candidate-dashboard/candidate-sidebar/candidate-sidebar.component.ts, src/app/endpoints/endpoint.ts, src/app/hr-dashboard/sidebar/sidebar.component.ts, src/app/interviewer-dashboard/sidebar/sidebar.component.ts, src/app/shared/services/login-signup.service.ts
1. fix available time slots for interviewer
2. previous application lists for candidate-dashboard
3. logout api integrated
=> Frontend integration/report gen

src/app/candidate-dashboard/job-details/job-details.component.ts
add skill, subskill name on job details view
=> add skill and subskill name on job views

backend/Api/Server/CVEndpoint.cs, backend/Shared/Authorization/TMPermissions.cs
fix: give file upload permissions to the cadidate
=> fix: give file upload permissions to the cadidate
